[package]
name = "vcard-rs"
description = "vCard parser, validator, editor and builder library for Rust"
version = "0.2.1"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.88"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["data-structures", "parser-implementations", "encoding", "no-std"]
keywords = ["vcard", "contact", "carddav", "rfc6350", "codec"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/vcard-rs/latest/vcard"
repository = "https://github.com/pimalaya/vcard"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "vcard"

[features]
default = ["parser", "quoted-printable", "base64", "encoding"]
parser = ["dep:memchr"]
jcard = ["parser", "dep:serde_json"]
jscontact = ["jcard"]
quoted-printable = ["dep:quoted_printable"]
base64 = ["dep:base64"]
encoding = ["dep:encoding_rs"]

[[bench]]
name = "parse"
path = "benches/parse.rs"
harness = false
required-features = ["parser"]

[[example]]
name = "parse_edit_export"
path = "examples/parse_edit_export.rs"
required-features = ["parser"]

[[example]]
name = "strict_builder"
path = "examples/strict_builder.rs"
required-features = ["parser"]

[[example]]
name = "raw_builder"
path = "examples/raw_builder.rs"
required-features = ["parser"]

[dev-dependencies]
calcard = { version = "0.3", default-features = false }
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
ical_vcard = { version = "0.5", default-features = false }
proptest = { version = "1", default-features = false, features = ["bit-set", "std"] }
vcard_parser = { version = "0.2", default-features = false }
vparser = { version = "1", default-features = false }

[dependencies]
base64 = { version = "0.23", default-features = false, features = ["alloc"], optional = true }
encoding_rs = { version = "0.8", default-features = false, features = ["alloc"], optional = true }
memchr = { version = "2", default-features = false, optional = true }
quoted_printable = { version = "0.5", default-features = false, optional = true }
serde_json = { version = "1", default-features = false, features = ["alloc"], optional = true }
