//! # Parameters (syntax side)
//!
//! The raw parameter node and the per-parameter lens markers.
//!
//! [`VcardParamNode`] is the syntactic peer of the decoded
//! [`VcardParam`](crate::param::VcardParam): a name leaf and its raw value
//! leaves, parsed from and serialized back to the wire verbatim. Below it sit the
//! lens markers, one zero-sized type per RFC 6350 parameter, generated by the
//! `scalar_param!` / `list_param!` macros; each ties a wire name to the
//! decoded shape ([`Cow`] for single-valued, [`Vec`] for multi-valued) and
//! delegates the codec to [`unescape`](crate::tree::decode). These markers are
//! the type-level keys for [`VcardLine::param`](crate::tree::line::VcardLine::param);
//! the name dispatch for whole-line decoding lives in [`crate::tree::decode`].

use core::fmt;

use alloc::{borrow::Cow, string::ToString, vec, vec::Vec};

use crate::{
    param::{
        VCARD_ALTID, VCARD_CALSCALE, VCARD_GEO, VCARD_LABEL, VCARD_LANGUAGE, VCARD_MEDIATYPE,
        VCARD_PID, VCARD_PREF, VCARD_SORT_AS, VCARD_TYPE, VCARD_TZ, VCARD_VALUE,
    },
    tree::{decode::unescape, leaf::VcardLeaf, lens::VcardParamLens},
};

/// One raw parameter: a name and its `,`-separated raw values (empty when the
/// parameter has no `=` list). The syntactic peer of the decoded
/// [`VcardParam`](crate::param::VcardParam).
#[derive(Clone, Debug)]
pub struct VcardParamNode<'a> {
    /// The parameter name leaf.
    pub name: VcardLeaf<'a>,
    /// The raw value leaves.
    pub values: Vec<VcardLeaf<'a>>,
}

impl<'a> VcardParamNode<'a> {
    /// Parse one `name=value,value` parameter (commas outside quotes split).
    pub fn parse(param: &'a str) -> Self {
        match param.split_once('=') {
            Some((name, values)) => Self {
                name: VcardLeaf::from(name),
                values: split_param_values(values)
                    .into_iter()
                    .map(VcardLeaf::from)
                    .collect(),
            },
            None => Self {
                name: VcardLeaf::from(param),
                values: Vec::new(),
            },
        }
    }
}

impl fmt::Display for VcardParamNode<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name.get())?;

        if let Some((first, rest)) = self.values.split_first() {
            write!(f, "={}", first.get())?;
            for value in rest {
                write!(f, ",{}", value.get())?;
            }
        }

        Ok(())
    }
}

/// Define a single-valued parameter lens (decoded as one [`Cow`]).
macro_rules! scalar_param {
    ($marker:ident, $name:path) => {
        #[doc = concat!("The `", stringify!($marker), "` parameter lens.")]
        #[allow(non_camel_case_types)]
        pub struct $marker;

        impl VcardParamLens for $marker {
            const NAME: &'static str = $name;

            type Target<'v> = Cow<'v, str>;

            fn decode<'v>(param: &'v VcardParamNode<'_>) -> Cow<'v, str> {
                param
                    .values
                    .first()
                    .map(|v| unescape(v.get()))
                    .unwrap_or_default()
            }

            fn encode(decoded: &Cow<'_, str>) -> VcardParamNode<'static> {
                VcardParamNode {
                    name: VcardLeaf::from($name.to_string()),
                    values: vec![VcardLeaf::from(decoded.to_string())],
                }
            }
        }
    };
}

/// Define a multi-valued parameter lens (decoded as a [`Vec`] of [`Cow`]).
macro_rules! list_param {
    ($marker:ident, $name:path) => {
        #[doc = concat!("The `", stringify!($marker), "` parameter lens.")]
        #[allow(non_camel_case_types)]
        pub struct $marker;

        impl VcardParamLens for $marker {
            const NAME: &'static str = $name;

            type Target<'v> = Vec<Cow<'v, str>>;

            fn decode<'v>(param: &'v VcardParamNode<'_>) -> Vec<Cow<'v, str>> {
                param.values.iter().map(|v| unescape(v.get())).collect()
            }

            #[allow(clippy::ptr_arg)]
            fn encode(decoded: &Vec<Cow<'_, str>>) -> VcardParamNode<'static> {
                VcardParamNode {
                    name: VcardLeaf::from($name.to_string()),
                    values: decoded
                        .iter()
                        .map(|v| VcardLeaf::from(v.to_string()))
                        .collect(),
                }
            }
        }
    };
}

scalar_param!(LANGUAGE, VCARD_LANGUAGE);
scalar_param!(VALUE, VCARD_VALUE);
scalar_param!(PREF, VCARD_PREF);
scalar_param!(ALTID, VCARD_ALTID);
scalar_param!(MEDIATYPE, VCARD_MEDIATYPE);
scalar_param!(CALSCALE, VCARD_CALSCALE);
scalar_param!(GEO, VCARD_GEO);
scalar_param!(TZ, VCARD_TZ);
scalar_param!(LABEL, VCARD_LABEL);

list_param!(PID, VCARD_PID);
list_param!(TYPE, VCARD_TYPE);
list_param!(SORT_AS, VCARD_SORT_AS);

/// Split a parameter value list on commas outside double quotes.
fn split_param_values(values: &str) -> Vec<&str> {
    let bytes = values.as_bytes();
    let mut pieces = Vec::new();
    let mut start = 0;
    let mut quoted = false;

    for (i, &byte) in bytes.iter().enumerate() {
        match byte {
            b'"' => quoted = !quoted,
            b',' if !quoted => {
                pieces.push(&values[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }
    pieces.push(&values[start..]);

    pieces
}

#[cfg(test)]
mod tests {
    use alloc::{borrow::Cow, string::ToString, vec};

    use crate::tree::{
        lens::VcardParamLens,
        param::{LANGUAGE, PID, VcardParamNode},
    };

    #[test]
    fn parses_quoted_values_then_round_trips() {
        let node = VcardParamNode::parse(r#"TYPE=work,"a,b""#);
        assert_eq!(node.values.len(), 2);
        assert_eq!(node.to_string(), r#"TYPE=work,"a,b""#);
    }

    #[test]
    fn decodes_a_list_parameter_through_its_lens() {
        let node = VcardParamNode::parse("PID=1,2");
        assert_eq!(
            PID::decode(&node),
            vec![Cow::Borrowed("1"), Cow::Borrowed("2")],
        );
    }

    #[test]
    fn encodes_a_scalar_parameter_through_its_lens() {
        let node = LANGUAGE::encode(&Cow::Borrowed("en"));
        assert_eq!(node.to_string(), "LANGUAGE=en");
    }
}
