//! # Property lenses
//!
//! The per-property lens markers: one zero-sized type per RFC 6350 property,
//! tying its wire name to the value kind it decodes to.
//!
//! Most properties share a value kind, so their lenses are identical but for the
//! name and the target type; they are generated by the `prop_lens!` macro,
//! which delegates `decode`/`encode` to the value type and hands out the generic
//! [`VcardValueCursor`] for editing. The one
//! genuinely structured exception with a bespoke cursor, `N`, lives in its own
//! [`n`] submodule. These markers are the type-level keys for
//! [`VcardCst::prop`](crate::tree::cst::VcardCst::prop) and friends; the name
//! dispatch for whole-card decoding lives in [`crate::tree::decode`].

pub mod n;

use crate::{
    prop::{
        VCARD_ADR, VCARD_ANNIVERSARY, VCARD_BDAY, VCARD_CALADRURI, VCARD_CALURI, VCARD_CATEGORIES,
        VCARD_CLIENTPIDMAP, VCARD_EMAIL, VCARD_FBURL, VCARD_FN, VCARD_GENDER, VCARD_GEO,
        VCARD_IMPP, VCARD_KEY, VCARD_KIND, VCARD_LANG, VCARD_LOGO, VCARD_MEMBER, VCARD_NICKNAME,
        VCARD_NOTE, VCARD_ORG, VCARD_PHOTO, VCARD_PRODID, VCARD_RELATED, VCARD_REV, VCARD_ROLE,
        VCARD_SOUND, VCARD_SOURCE, VCARD_TEL, VCARD_TITLE, VCARD_TZ, VCARD_UID, VCARD_URL,
        VCARD_XML,
    },
    tree::{cursor::VcardValueCursor, lens::VcardPropLens, line::VcardLine, value::VcardValueNode},
    value::{
        adr::VcardAdr,
        client_pid_map::VcardClientPidMap,
        datetime::{VcardDateAndOrTime, VcardTimestamp},
        gender::VcardGender,
        language::VcardLanguageTag,
        org::VcardOrg,
        text::{VcardText, VcardTextList},
        uri::VcardUri,
    },
};

/// Define a property lens marker that delegates to a shared value type and edits
/// through the generic [`VcardValueCursor`].
macro_rules! prop_lens {
    ($marker:ident, $name:path, $value:ident) => {
        #[doc = concat!("The `", stringify!($marker), "` property lens.")]
        #[allow(non_camel_case_types)]
        pub struct $marker;

        impl VcardPropLens for $marker {
            const NAME: &'static str = $name;

            type Target<'v> = $value<'v>;

            type Cursor<'c, 'a>
                = VcardValueCursor<'c, 'a>
            where
                'a: 'c;

            fn decode<'v>(value: &'v VcardValueNode<'_>) -> $value<'v> {
                $value::decode(value)
            }

            fn encode(decoded: &$value<'_>) -> VcardValueNode<'static> {
                decoded.encode()
            }

            fn cursor<'c, 'a>(line: &'c mut VcardLine<'a>) -> VcardValueCursor<'c, 'a> {
                VcardValueCursor { line }
            }
        }
    };
}

prop_lens!(FN, VCARD_FN, VcardText);
prop_lens!(KIND, VCARD_KIND, VcardText);
prop_lens!(XML, VCARD_XML, VcardText);
prop_lens!(TEL, VCARD_TEL, VcardText);
prop_lens!(EMAIL, VCARD_EMAIL, VcardText);
prop_lens!(TITLE, VCARD_TITLE, VcardText);
prop_lens!(ROLE, VCARD_ROLE, VcardText);
prop_lens!(NOTE, VCARD_NOTE, VcardText);
prop_lens!(PRODID, VCARD_PRODID, VcardText);
prop_lens!(TZ, VCARD_TZ, VcardText);

prop_lens!(NICKNAME, VCARD_NICKNAME, VcardTextList);
prop_lens!(CATEGORIES, VCARD_CATEGORIES, VcardTextList);

prop_lens!(SOURCE, VCARD_SOURCE, VcardUri);
prop_lens!(PHOTO, VCARD_PHOTO, VcardUri);
prop_lens!(IMPP, VCARD_IMPP, VcardUri);
prop_lens!(LOGO, VCARD_LOGO, VcardUri);
prop_lens!(MEMBER, VCARD_MEMBER, VcardUri);
prop_lens!(RELATED, VCARD_RELATED, VcardUri);
prop_lens!(SOUND, VCARD_SOUND, VcardUri);
prop_lens!(UID, VCARD_UID, VcardUri);
prop_lens!(GEO, VCARD_GEO, VcardUri);
prop_lens!(URL, VCARD_URL, VcardUri);
prop_lens!(KEY, VCARD_KEY, VcardUri);
prop_lens!(FBURL, VCARD_FBURL, VcardUri);
prop_lens!(CALADRURI, VCARD_CALADRURI, VcardUri);
prop_lens!(CALURI, VCARD_CALURI, VcardUri);

prop_lens!(BDAY, VCARD_BDAY, VcardDateAndOrTime);
prop_lens!(ANNIVERSARY, VCARD_ANNIVERSARY, VcardDateAndOrTime);

prop_lens!(REV, VCARD_REV, VcardTimestamp);
prop_lens!(LANG, VCARD_LANG, VcardLanguageTag);

prop_lens!(ADR, VCARD_ADR, VcardAdr);
prop_lens!(GENDER, VCARD_GENDER, VcardGender);
prop_lens!(ORG, VCARD_ORG, VcardOrg);
prop_lens!(CLIENTPIDMAP, VCARD_CLIENTPIDMAP, VcardClientPidMap);
